language: node_js
node_js:
- '5.2'
cache:
  directories:
  - node_modules
before_script:
- npm install -g ava
- npm install -g mversion
- git config --global user.email "tusharmath@gmail.com"
- git config --global user.name "Travis-CI"
before_deploy:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- mversion patch -m
deploy:
  provider: npm
  email: tusharmath@gmail.com
  on:
    branch: master
  api_key:
    secure: p4JQxCc2hlNuMyU9MrQYf09pJ+cD6vB1tWhfgsHG1otDdjRNHXzPoKxLsUMzup1pV5pKBqRRFq7iahGn3NBndjMY8sr0wlMzBozJXpd6cKBZAvyNSX9+IQUzw/8R2l/GGoUvQDn0iNmgdjvW3Y1cKXvF+Vl7G1M+uW8tmkkHHeIqG/yCwnxSIBle2vwcO6jBr7UP2pjoRj8OJvFcx81q4UgAYTqb2n/y7kZ94I8maAQRoQaoC5gDVyuOFDKcagSDtqRjLwgReB4ymaNAJn5KahuGncb2FGRXF3AwzGB5S34RRqbpJPHgD6lmery+JqgTj4T0rWPxjPlOduomwUcNeqZC6KvpYpApjXW1PGnd89sYVnXtcRqnFR3sZ53Ae+VxAnW5VUK0y9olwlNZ78i0TOwRK9SbJjh8gEHTqsJfbLRFhrdyRY/xFTuPhEonX3wU3DyMNJuBqOalcIKCcWKqrUtQjUdhyrGx/L1UNFbXShBucmerevhT2GQ/DBGuH/VfaA2FuC387ndODEWwJwPmtiSpcp/nIu0yEZU+naf9qs+wJ2PhVHo+CFQELjaS9H8fwzQNYbItSolyXNw0g28j+TCL9T5tIIV1m2u0WTCedkILQGwXY7JrdqhizrM2dlKdbdBLnGft/b9NSmv2xYmugWn7qP5uy63mUcEpm9sMGgA=
env:
  global:
    secure: HXUgpy8JalhYxkiC4fg7aA7z2zklWFs+fTK/B8+x4uQ8Jp+Tu0xSYkWLOpEgN3lwJiAuX9pLoIEKR1TPkyZNF4hkSXsqxse/JA8BUwC/+PfCSUWPEBGDNrHSSf1fgQAb+h10NKQYjRExJX3ZdMr5/aAtCWmXrrgolrOPUZtZgXVK6dHt1nWhQjOePbcfH6auYGbTZD7Bdjma9XVXO+1j+sYfvg+dWBhIY4KmYdpZsrcYwB6BCAKLXm1Kf9FXdUrbkGgwx5PyFctXDZvJyUW8GiO5d8hpEGUNvfjbcVePlYE0VY3ZBo7biIQubN/xFLIonzpQOV3TY8Db+4vbb4v5vQvYYrBLTMgiHW4zDA92HjbMK+NgMrvGw0R73yC2lmZ8ly5fAdEPIimhu++xvw3yPqfIfrFGdYlyi5tNhXfGmYyUsS8umFvyiHUxUSEq5WzZvGeYyWnc9TJ9PD8wly1vGn5M4T4s6LYg51gSBVqJx50lmuEke+o9+BPbckjmsQq6D3lDP7mKLIkTAhFdGWF6o7XhcZ/eT3N+natsdCYTYckqWMzomimwgMCGVvW1i9aGHLDrpw29URTAdeV7kTveTvw5L+tUQ7ZroqJirAxBq0t/xC82V+BoN5yBlXABjn6/2GxBadoG25Zx1GudmacyVjEn8ls38Fi95DTcRX1mQdo=
