language: node_js
node_js:
- '5.2'
cache:
  directories:
  - node_modules
before_script:
- npm install -g ava
deploy:
  provider: npm
  email: tusharmath@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: HXUgpy8JalhYxkiC4fg7aA7z2zklWFs+fTK/B8+x4uQ8Jp+Tu0xSYkWLOpEgN3lwJiAuX9pLoIEKR1TPkyZNF4hkSXsqxse/JA8BUwC/+PfCSUWPEBGDNrHSSf1fgQAb+h10NKQYjRExJX3ZdMr5/aAtCWmXrrgolrOPUZtZgXVK6dHt1nWhQjOePbcfH6auYGbTZD7Bdjma9XVXO+1j+sYfvg+dWBhIY4KmYdpZsrcYwB6BCAKLXm1Kf9FXdUrbkGgwx5PyFctXDZvJyUW8GiO5d8hpEGUNvfjbcVePlYE0VY3ZBo7biIQubN/xFLIonzpQOV3TY8Db+4vbb4v5vQvYYrBLTMgiHW4zDA92HjbMK+NgMrvGw0R73yC2lmZ8ly5fAdEPIimhu++xvw3yPqfIfrFGdYlyi5tNhXfGmYyUsS8umFvyiHUxUSEq5WzZvGeYyWnc9TJ9PD8wly1vGn5M4T4s6LYg51gSBVqJx50lmuEke+o9+BPbckjmsQq6D3lDP7mKLIkTAhFdGWF6o7XhcZ/eT3N+natsdCYTYckqWMzomimwgMCGVvW1i9aGHLDrpw29URTAdeV7kTveTvw5L+tUQ7ZroqJirAxBq0t/xC82V+BoN5yBlXABjn6/2GxBadoG25Zx1GudmacyVjEn8ls38Fi95DTcRX1mQdo=
